/**
 * scripts/keygen.ts (plan step R4, #2982): the solana-keygen file format,
 * mode 0600 under any umask, the refusals (existing file, a path git could
 * pick up, key-shaped or missing arguments), and that nothing but the base58
 * public key is ever printed.
 *
 * Every key here is a throwaway generated by the test into a temp directory
 * (outside any git worktree) and deleted afterwards.
 */
import { spawnSync } from "node:child_process";
import { createPrivateKey, createPublicKey } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { encodeBase58 } from "../src/base58.ts";
import { readKeypairSigner } from "../scripts/lib/keyfile.ts";
import { tempDir } from "./admin-helpers.ts";

const repo = new URL("..", import.meta.url).pathname;
const dir = tempDir("gogocash-keygen-");
afterAll(() => rmSync(dir, { recursive: true, force: true }));

const PKCS8_ED25519_PREFIX = Buffer.from("302e020100300506032b657004220420", "hex");

/** Node prints an ExperimentalWarning for type stripping on some versions; nothing else may reach stderr. */
function cleanStderr(stderr: string): string {
  return stderr.replace(/^.*ExperimentalWarning.*\n?/gm, "").replace(/^\(Use .*\n?/gm, "");
}

/** Runs keygen under `umask <mask>` (the script must still write mode 0600). */
function keygen(args: readonly string[], options: { umask?: string; cwd?: string } = {}) {
  const run = spawnSync(
    "/bin/sh",
    ["-c", `umask ${options.umask ?? "022"} && exec "$0" "$@"`, process.execPath, join(repo, "scripts/keygen.ts"), ...args],
    { cwd: options.cwd ?? repo, encoding: "utf8" },
  );
  return { status: run.status, stdout: run.stdout, stderr: cleanStderr(run.stderr) };
}

function publicKeyFromSeed(seed: Uint8Array): Uint8Array {
  const privateKey = createPrivateKey({ key: Buffer.concat([PKCS8_ED25519_PREFIX, seed]), format: "der", type: "pkcs8" });
  const spki = createPublicKey(privateKey).export({ format: "der", type: "spki" });
  return Uint8Array.from(spki.subarray(spki.length - 32));
}

/** Every encoding of the secret an accidental print could use. */
function secretRenderings(secret: Uint8Array): string[] {
  const seed = Buffer.from(secret.subarray(0, 32));
  const full = Buffer.from(secret);
  return [
    JSON.stringify([...full]),
    [...full].join(","),
    full.toString("hex"),
    seed.toString("hex"),
    full.toString("base64"),
    seed.toString("base64"),
    encodeBase58(full),
    encodeBase58(seed),
    // A run of the first eight seed bytes as they appear in the file.
    [...seed.subarray(0, 8)].join(","),
  ];
}

describe("scripts/keygen.ts", () => {
  it("writes the 64-byte solana-keygen array (seed, then its public key) and prints only the public key", async () => {
    const out = join(dir, "deployer.json");
    const run = keygen(["--out", out]);
    expect(run.stderr).toBe("");
    expect(run.status).toBe(0);

    const text = readFileSync(out, "utf8");
    expect(text).toMatch(/^\[(\d{1,3},){63}\d{1,3}\]$/);
    const values = JSON.parse(text) as number[];
    expect(values).toHaveLength(64);
    expect(values.every((v) => Number.isInteger(v) && v >= 0 && v <= 255)).toBe(true);
    const secret = Uint8Array.from(values);
    const publicKey = publicKeyFromSeed(secret.subarray(0, 32));
    expect(Buffer.from(secret.subarray(32)).equals(Buffer.from(publicKey))).toBe(true);

    // stdout is exactly the base58 public key and a newline.
    expect(run.stdout).toBe(`${encodeBase58(publicKey)}\n`);
    expect(run.stdout).toMatch(/^[1-9A-HJ-NP-Za-km-z]{32,44}\n$/);
    for (const rendering of secretRenderings(secret)) {
      expect(run.stdout.includes(rendering)).toBe(false);
      expect(run.stderr.includes(rendering)).toBe(false);
    }

    // The file loads as a signer with the printed address (the admin CLI's loader).
    const signer = await readKeypairSigner(out);
    expect(signer.address).toBe(run.stdout.trim());
  });

  it("writes mode 0600 even under umask 000, and creates missing parent directories mode 0700", () => {
    const parent = join(dir, "nested", "devnet");
    const out = join(parent, "admin.json");
    const run = keygen(["--out", out], { umask: "000" });
    expect(run.stderr).toBe("");
    expect(run.status).toBe(0);
    expect(statSync(out).mode & 0o777).toBe(0o600);
    expect(statSync(parent).mode & 0o777).toBe(0o700);
    expect(statSync(join(dir, "nested")).mode & 0o777).toBe(0o700);
  });

  it("two runs give two different keys", () => {
    const a = keygen(["--out", join(dir, "a.json")]);
    const b = keygen(["--out", join(dir, "b.json")]);
    expect(a.status).toBe(0);
    expect(b.status).toBe(0);
    expect(a.stdout).not.toBe(b.stdout);
  });

  it("never overwrites an existing file, and leaves no temp file behind", () => {
    const out = join(dir, "existing.json");
    writeFileSync(out, "operator data", { mode: 0o600 });
    const run = keygen(["--out", out]);
    expect(run.status).toBe(2);
    expect(run.stdout).toBe("");
    expect(run.stderr).toMatch(/already exists; keygen never overwrites a key/);
    expect(readFileSync(out, "utf8")).toBe("operator data");
    const leftovers = spawnSync("ls", ["-A", dir], { encoding: "utf8" }).stdout;
    expect(leftovers).not.toMatch(/\.keygen-/);
  });

  it("refuses a path inside a git worktree that is not git-ignored, and accepts an ignored one", () => {
    const worktree = join(dir, "worktree");
    mkdirSync(worktree);
    const init = spawnSync("git", ["init", "-q", worktree], { encoding: "utf8" });
    expect(init.status).toBe(0);
    writeFileSync(join(worktree, ".gitignore"), "keys/\n");

    const tracked = join(worktree, "src", "deployer.json");
    const refused = keygen(["--out", tracked]);
    expect(refused.status).toBe(2);
    expect(refused.stdout).toBe("");
    expect(refused.stderr).toMatch(/inside a git worktree and not git-ignored/);
    expect(existsSync(tracked)).toBe(false);
    expect(existsSync(join(worktree, "src"))).toBe(false);

    // The repository's own tree is refused too (scripts/ is tracked, not ignored).
    const inRepo = join(repo, "scripts", "keygen-test-should-never-exist.json");
    const refusedInRepo = keygen(["--out", inRepo]);
    expect(refusedInRepo.status).toBe(2);
    expect(existsSync(inRepo)).toBe(false);

    const ignored = join(worktree, "keys", "devnet", "guardian.json");
    const accepted = keygen(["--out", ignored]);
    expect(accepted.stderr).toBe("");
    expect(accepted.status).toBe(0);
    expect(statSync(ignored).mode & 0o777).toBe(0o600);
  });

  it("refuses a missing --out, unknown options and key-shaped values without echoing them", () => {
    const missing = keygen([]);
    expect(missing.status).toBe(2);
    expect(missing.stderr).toMatch(/--out is required/);

    const unknown = keygen(["--secret", "x"]);
    expect(unknown.status).toBe(2);
    expect(unknown.stderr).toMatch(/unknown option --secret/);

    // A pasted key array, base58 secret or hex seed given as an argument.
    const pastedArray = `[${Array.from({ length: 64 }, (_, i) => (i * 7) % 256).join(",")}]`;
    const pastedBase58 = encodeBase58(Uint8Array.from({ length: 64 }, (_, i) => (i * 13 + 1) % 256));
    const pastedHex = "ab".repeat(32);
    for (const pasted of [pastedArray, pastedBase58, pastedHex]) {
      for (const argv of [["--out", pasted], [pasted]]) {
        const run = keygen(argv);
        expect(run.status).toBe(2);
        expect(run.stdout).toBe("");
        expect(run.stderr.includes(pasted)).toBe(false);
      }
    }
    expect(existsSync(join(repo, pastedArray))).toBe(false);
  });

  it("--help prints usage to stderr and writes nothing", () => {
    const run = keygen(["--help"]);
    expect(run.status).toBe(0);
    expect(run.stdout).toBe("");
    expect(run.stderr).toMatch(/Usage: node scripts\/keygen.ts --out/);
  });
});
