/**
 * The demo's evidence file, `evidence/devnet-demo-<date>.md`, pure: the
 * record type, the Markdown renderer and the guard every text passes before
 * it is written.
 *
 * The file holds public data only (addresses, signatures, amounts,
 * outcomes) and devnet Explorer links. The guard refuses the shapes key
 * material takes: a JSON array of 32 or more numbers (a seed, or a 64-byte
 * keypair file), and any 64-byte-sized base58 value that is not one of the
 * run's own transaction signatures. It also refuses any caller-named
 * forbidden text, which the demo uses for the RPC URL.
 */

export type StepOutcome = "PASS" | "FAIL" | "SKIPPED";

export type EvidenceSignature = { readonly label: string; readonly signature: string };

export type EvidenceStep = {
  readonly number: number;
  readonly title: string;
  readonly expected: string;
  readonly observed: string;
  readonly outcome: StepOutcome;
  readonly details: readonly string[];
  readonly signatures: readonly EvidenceSignature[];
  /** Text shown verbatim in a code block (the consent message). */
  readonly verbatim?: string;
};

export type DemoEvidence = {
  /** `YYYY-MM-DD` (UTC). */
  readonly date: string;
  /** ISO 8601 UTC. */
  readonly generatedAt: string;
  readonly command: string;
  readonly genesisHash: string;
  readonly programId: string;
  readonly vault: {
    readonly name: string;
    readonly address: string;
    readonly mint: string;
    readonly tokenAccount: string;
  };
  readonly roles: {
    readonly claimAuthority: string;
    readonly guardian: string;
    readonly admin: string;
    readonly payer: string;
    readonly recipient: string;
  };
  readonly steps: readonly EvidenceStep[];
};

export const EXPLORER_BASE_URL = "https://explorer.solana.com";

/** The devnet Explorer page of a transaction. */
export function explorerTxUrl(signature: string): string {
  return `${EXPLORER_BASE_URL}/tx/${signature}?cluster=devnet`;
}

/** The devnet Explorer page of an account. */
export function explorerAddressUrl(accountAddress: string): string {
  return `${EXPLORER_BASE_URL}/address/${accountAddress}?cluster=devnet`;
}

/** `YYYY-MM-DD` (UTC) of epoch milliseconds. */
export function evidenceDate(epochMs: number): string {
  return new Date(epochMs).toISOString().slice(0, 10);
}

/** `devnet-demo-<date>.md`, then `devnet-demo-<date>-2.md`, `-3`, ... for later runs the same day. */
export function evidenceFileName(date: string, attempt = 1): string {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new TypeError("date must be YYYY-MM-DD.");
  if (!Number.isSafeInteger(attempt) || attempt < 1) throw new TypeError("attempt must be a positive integer.");
  return attempt === 1 ? `devnet-demo-${date}.md` : `devnet-demo-${date}-${attempt}.md`;
}

/** PASS only when every step passed. */
export function overallOutcome(steps: readonly EvidenceStep[]): "PASS" | "FAIL" {
  return steps.length > 0 && steps.every((step) => step.outcome === "PASS") ? "PASS" : "FAIL";
}

function cell(text: string): string {
  return text.replace(/\r?\n/g, " ").replace(/\|/g, "\\|");
}

function addressLink(value: string): string {
  return `[\`${value}\`](${explorerAddressUrl(value)})`;
}

/** Renders the evidence record as Markdown (LF line endings, trailing LF). */
export function renderEvidence(evidence: DemoEvidence): string {
  const passed = evidence.steps.filter((step) => step.outcome === "PASS").length;
  const lines: string[] = [
    `# Devnet demo evidence (${evidence.date})`,
    "",
    `Result: **${overallOutcome(evidence.steps)}** (${passed} of ${evidence.steps.length} steps passed).`,
    "",
    `Generated by \`${evidence.command}\` at ${evidence.generatedAt} (plan step R5, mygogocash/gogocash-monorepo#2983). ` +
      "This file holds public data only: addresses, signatures, amounts and outcomes. " +
      "It holds no key material and no RPC URL. The links open the devnet Explorer.",
    "",
    "## Deployment",
    "",
    "| Item | Value |",
    "| --- | --- |",
    `| Cluster | devnet, genesis hash \`${evidence.genesisHash}\` |`,
    `| Program | ${addressLink(evidence.programId)} |`,
    `| Vault \`${cell(evidence.vault.name)}\` | ${addressLink(evidence.vault.address)} |`,
    `| Mint | ${addressLink(evidence.vault.mint)} |`,
    `| Vault token account | ${addressLink(evidence.vault.tokenAccount)} |`,
    `| Claim authority | ${addressLink(evidence.roles.claimAuthority)} |`,
    `| Guardian | ${addressLink(evidence.roles.guardian)} |`,
    `| Admin | ${addressLink(evidence.roles.admin)} |`,
    `| Fee payer | ${addressLink(evidence.roles.payer)} |`,
    `| Stand-in member wallet (made in memory for this run) | ${addressLink(evidence.roles.recipient)} |`,
    "",
    "## Steps",
    "",
    "| # | Step | Expected | Observed | Result |",
    "| --- | --- | --- | --- | --- |",
    ...evidence.steps.map(
      (step) => `| ${step.number} | ${cell(step.title)} | ${cell(step.expected)} | ${cell(step.observed)} | ${step.outcome} |`,
    ),
  ];
  for (const step of evidence.steps) {
    lines.push("", `## ${step.number}. ${step.title} (${step.outcome})`, "");
    for (const detail of step.details) lines.push(`- ${detail}`);
    if (step.verbatim !== undefined) {
      if (step.details.length > 0) lines.push("");
      lines.push("```text", step.verbatim, "```");
    }
    if (step.signatures.length > 0) {
      lines.push("", "| Transaction | Signature |", "| --- | --- |");
      for (const s of step.signatures) {
        lines.push(`| ${cell(s.label)} | [\`${s.signature}\`](${explorerTxUrl(s.signature)}) |`);
      }
    }
  }
  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// The guard
// ---------------------------------------------------------------------------

/** A JSON array of 32 or more integers: the shape of a seed or a keypair file. */
const BYTE_ARRAY = /\[\s*(?:\d{1,3}\s*,\s*){31,}\d{1,3}\s*\]/;
/** Base58 runs as long as a 64-byte value (a signature, or a secret key). */
const LONG_BASE58 = /[1-9A-HJ-NP-Za-km-z]{80,}/g;

/**
 * Every reason `text` must not be written. `allowedLongValues` lists the
 * 64-byte base58 values the text may hold (the run's transaction and consent
 * signatures); `forbidden` lists values that must not appear at all (the RPC
 * URL and its host).
 */
export function evidenceProblems(
  text: string,
  options: { readonly allowedLongValues: readonly string[]; readonly forbidden: readonly string[] },
): string[] {
  const problems: string[] = [];
  if (BYTE_ARRAY.test(text)) problems.push("it holds a JSON array of 32 or more numbers (the shape of key bytes).");
  const allowed = new Set(options.allowedLongValues);
  for (const match of text.match(LONG_BASE58) ?? []) {
    if (!allowed.has(match)) {
      problems.push("it holds a 64-byte-sized base58 value that is not one of the run's signatures.");
      break;
    }
  }
  for (const value of options.forbidden) {
    if (value.length >= 4 && text.includes(value)) {
      problems.push("it holds a forbidden value (the RPC URL or its host).");
      break;
    }
  }
  return problems;
}
